* Spmaster

3. add in a sound effect when they submit a word
5. everything lower-case automatically when typing a hint.
6. Add a timer.
7. Make it where the word-buttons things don't change your cursor.

* Misc

** xps 9360 backlight issue?
   I haven't figured out exactly what the cause of it was, but it seems like
   hibernation or sleep can cause issues with this laptop's screen backlight. At
   some point (I think after waking it up from either hibernation or sleep,
   though I can't really remember for sure) the backlight got stuck on max
   brightness. One thing that was weird about this is the bios has a brightness
   control (for some reason) and it was still working so I was pretty sure it
   wasn't a hardware issue. I did try installing windows and it didn't seem to
   fix the problem there either, but I was focused on trying to apply a patch
   (for a previous generation) so I might have missed it. Either way, I was able
   to fix the problem by running these 3 commands, though I think it was just
   the third that fixed it.
   #+BEGIN_SRC sh
     systemctl suspend
     pm-suspend
     pm-hibernate
   #+END_SRC
*** EDIT
    Turns out the actual problem was a hardware thing.
** xps 9360 tap-to-click issue
   Another weird one. If I go into normal gnome, there is an option in the
   settings to disable tap-to-click. When I use that, it works correctly,
   however, if I try to disable tap-to-click in xmonad, it doesn't work
   correctly with adding this into
   =/usr/share/X11/xorg.conf.d/51-synaptics-quirks.conf=
   #+BEGIN_SRC sh
     # Disable generic Synaptics device, as we're using
     # "DLL075B:01 06CB:76AF Touchpad"
     # Having multiple touchpad devices running confuses syndaemon
     Section "InputClass"
     Identifier "SynPS/2 Synaptics TouchPad"
     MatchProduct "SynPS/2 Synaptics TouchPad"
     MatchIsTouchpad "on"
     MatchOS "Linux"
     MatchDevicePath "/dev/input/event*"
     Option "Ignore" "on"
     EndSection
   #+END_SRC
