#!/bin/bash
#
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running.
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

# Network manager
if [ -z "$(pgrep nm-applet)" ] ; then nm-applet --sm-disable & fi

# Synapse
if [ -z "$(pgrep synapse)" ] ; then synapse -s & fi

# Bluetooth
if [ -z "$(pgrep blueman-applet)" ] ; then blueman-applet & fi

# Set the default backlight setting to 30%
light -S 15
